### ISSUE TITLE
Showing below layer when scroll fast

### ISSUE THREAD

**Issue by Abdurahmon727** [Morfly/MultiState-BottomSheet#1]
When scrolling bottom sheet  fast it is showing below layer
device: android 13, samsung galaxy A32

https://github.com/user-attachments/assets/8727f485-961d-4f06-b709-bee44e3e2e31

**Comment by Morfly** [comment]
Hi @Abdurahmon727 
This library uses an [AnchoredDraggable](https://developer.android.com/reference/kotlin/androidx/compose/foundation/gestures/AnchoredDraggableState) component from standard Jetpack Compose library.  I'm afraid the behavior you see is caused by this component. If you check the standard bottom sheet released by Google, you will notice the same behavior.
